# frozen_string_literal: true

require 'minitest/autorun'
require_relative 'd07'

class TestD07 < Minitest::Test
  def setup
    @input = <<~INPUT
      .......S.......
      ...............
      .......^.......
      ...............
      ......^.^......
      ...............
      .....^.^.^.....
      ...............
      ....^.^...^....
      ...............
      ...^.^...^.^...
      ...............
      ..^...^.....^..
      ...............
      .^.^.^.^.^...^.
      ...............
    INPUT
  end

  def test_part1
    assert_equal 21, D07.new(@input).part1
  end

  def test_part2
    assert_equal 40, D07.new(@input).part2
  end
end
